<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="2" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="16665" started-at="2019-11-19T11:12:56Z" finished-at="2019-11-19T11:13:12Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="16665" started-at="2019-11-19T11:12:56Z" finished-at="2019-11-19T11:13:12Z">
      <class name="com.qa.executiontestcases.SingleUserExecution">
        <test-method status="PASS" signature="browserLaunch()[pri:0, instance:com.qa.executiontestcases.SingleUserExecution@3ec300f1]" name="browserLaunch" is-config="true" duration-ms="25370" started-at="2019-11-19T11:12:30Z" finished-at="2019-11-19T11:12:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserLaunch -->
        <test-method status="FAIL" signature="singleUserMultipleAccessExecution()[pri:0, instance:com.qa.executiontestcases.SingleUserExecution@3ec300f1]" name="singleUserMultipleAccessExecution" duration-ms="16606" started-at="2019-11-19T11:12:56Z" finished-at="2019-11-19T11:13:12Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertFalse(Assert.java:65)
at org.testng.Assert.assertFalse(Assert.java:75)
at com.ey.iiqcommons.elementpage.LoginElements.loginWithValidCredentials(LoginElements.java:75)
at com.qa.executiontestcases.SingleUserExecution.singleUserMultipleAccessExecution(SingleUserExecution.java:280)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- singleUserMultipleAccessExecution -->
      </class> <!-- com.qa.executiontestcases.SingleUserExecution -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
